
### Obtener todas las solicitudes
GET http://localhost:8000/aceptaciones?jefe_id=1

### Obtener una solicitud por ID
GET http://localhost:8000/aceptaciones/all?jefe_id=1

### SOLICITAR CAMBIO DE FECHA
PUT http://localhost:800/aceptaciones/cambio-fecha?val_jefe_id=1

### ACTUALIZAR ESTADO 
PUT http://localhost:8000/aceptaciones/actualizar?val_jefe_id=1

{
  "estado": "ACEPTADO",
  "observaciones": "Aprobado sin inconvenientes"
}